#!/usr/bin/env bash
# vim:set expandtab shiftwidth=4 filetype=bash:
# SPDX-License-Identifier: GPL-3.0-only

#
#
# ~chewygumxx/waybar-weather.git
# ::: :/scripts/curl-current-weather.sh
#
#

set -euo pipefail

: "${UNIT:=metric}"
: "${LOCATION:=Melbourne}"
: "${VISUALCROSSING_APIKEY:=$(pass-cli item view 'pass://pass-cli/api_visualcrossing/APIKEY')}"


get_raw_response() {
    curl \
        --silent \
        --retry 3 \
        --retry-delay 2 \
        --retry-all-errors \
        --show-error \
        --fail-with-body \
        --get \
        --data-urlencode 'iconSet=icons2' \
        --data-urlencode 'contentType=json' \
        --data-urlencode "unitGroup=$UNIT" \
        --data-urlencode "key=$VISUALCROSSING_APIKEY" \
        "https://weather.visualcrossing.com/VisualCrossingWebServices/rest/services/timeline/$LOCATION"
}

filter_current() {
    printf '%s\n' "$1" | jq '.currentConditions | {
        conditions,
        temp,
        icon
    }'
}

map_icon() {
    local color icon
    case "$1" in
        wind)                  color='#b3deef' icon="" ;;
        fog)                   color='#b3deef' icon="" ;;
        clear-day)             color='#ffc24b' icon="" ;;
        clear-night)           color='#cad6ff' icon="" ;;
        cloudy)                color='#aaaaaa' icon="" ;;
        partly-cloudy-night)   color='#cad6ff' icon="" ;;
        partly-cloudy-day)     color='#ffc24b' icon="" ;;
        rain)                  color='#7171d3' icon="" ;;
        showers-day)           color='#73cef4' icon="" ;;
        showers-night)         color='#73cef4' icon="" ;;
        thunder-rain)          color='#f0fb3e' icon="" ;;
        thunder-showers-day)   color='#f0fb3e' icon="" ;;
        thunder-showers-night) color='#f0fb3e' icon="" ;;
        snow)                  color='#e8e0ff' icon="" ;;
        snow-showers-day)      color='#e8e0ff' icon="" ;;
        snow-showers-night)    color='#e8e0ff' icon="" ;;
        *)                     color='#f43755' icon="" ;;
    esac

    printf '<span color="%s">%s<span>' "$color" "$icon"
}

unit_symbol() {
    case "$UNIT" in
        us)     printf '°F' ;;
        metric) printf '°C' ;;
        uk)     printf '°C' ;;
        base)   printf '°C' ;;
        *)      printf '°' ;;
    esac
}

emit_error() {
    jq -nc \
        --arg text "Error $(map_icon '')" \
        --arg tooltip "$1" \
        '{text: $text, tooltip: $tooltip}'
}

fetch_and_format() {
    local raw_response current_weather conditions temp icon text

    raw_response="$(get_raw_response)" || return 1
    current_weather="$(filter_current "$raw_response")" || return 1
    conditions="$(printf '%s\n' "$current_weather" | jq -r '.conditions')" || return 1
    temp="$(printf '%s\n' "$current_weather" | jq -r '.temp')" || return 1
    icon="$(printf '%s\n' "$current_weather" | jq -r '.icon')" || return 1

    text="$(printf '%s %s %s%s' \
        "$conditions" "$(map_icon "$icon")" "$temp" "$(unit_symbol)" )"

    jq -nc \
        --arg text "$text" \
        --arg tooltip "$conditions" \
        '{text: $text, tooltip: $tooltip}'
}

if output="$(fetch_and_format)"; then
    printf '%s\n' "$output"
else
    emit_error "Failed to retrieve weather for $LOCATION"
fi
