#!/usr/bin/env bash
# vim:set expandtab shiftwidth=4 filetype=bash:
# SPDX-License-Identifier: GPL-3.0-only

#
#
# ~chewygumxx/waybar-weather.git
# ::: :/.husky/commit-msg
#
#

npx --no -- commitlint --edit "$1"
