# vim:set expandtab shiftwidth=4 filetype=yaml foldlevel=5:
# SPDX-License-Identifier: GPL-3.0-only

#
#
# ~chewygumxx/waybar-weather.git
# ::: :/.github/workflows/verify-header-metadata.yaml
#
#

name: Verify Header Metadata

on:
    - push
    - pull_request

permissions:
    contents: read

jobs:
    verify:
        name: Verify
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v7

            - name: Verify tracked files
              uses: chewygumxx/sync-header-metadata@v2
              with:
                  mode:        verify
                  verbose:    'false'
                  annotation: 'false'
